[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel", "Cython"]

[tool.isort]
atomic = true
force_single_line = true
known_first_party = "pyzdf"
line_length = 88

[tool.black]
line-length = 88
target-version = ['py39']
